[package]
name = "MetabaseRCE_CVE-2023-38646"
version = "1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.23"
futures = "0.3"
tokio = { version = "1.12.0", features = ["full"] }
clap = { version = "4.0", features = ["cargo"] }
serde_json = "1.0.112"
base64 = "0.21.7"
colored = "2.1.0"
